/*
 * login delegation
 *
 * This is an api service for openshift to login with basic authentication
 *
 * API version: 1.0.0
 * Contact: yang.chenjun@99cloud.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"
	"path/filepath"
	// WARNING!
	// Change this to a fully-qualified import pat
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/simonyangcj/openshift_basic_authentication_demo/swagger"
)

func main() {

	log.Printf("Server started")
	router := sw.NewRouter()
	currentDir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
	// set cert and key path
	crt, key := currentDir + "/credentials/admin.crt", currentDir + "/credentials/admin.key"
	log.Fatal(http.ListenAndServeTLS(":9443", crt, key, router))
}
